// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWsD7dJU3FWencqXY1GIIiGJcgnGsBn8',
    appId: '1:1014270273523:web:e67d27da98178454f31486',
    messagingSenderId: '1014270273523',
    projectId: 'devprofileo',
    authDomain: 'devprofileo.firebaseapp.com',
    storageBucket: 'devprofileo.firebasestorage.app',
    measurementId: 'G-0CT9BY25VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOTZUsu7l_E7nSCukf7AZhV1-ozmf3Vk8',
    appId: '1:1014270273523:android:25fec5bf012a7bc6f31486',
    messagingSenderId: '1014270273523',
    projectId: 'devprofileo',
    storageBucket: 'devprofileo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.aprofileo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.aprofileo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtWsD7dJU3FWencqXY1GIIiGJcgnGsBn8',
    appId: '1:1014270273523:web:a8185bb29e9166f4f31486',
    messagingSenderId: '1014270273523',
    projectId: 'devprofileo',
    authDomain: 'devprofileo.firebaseapp.com',
    storageBucket: 'devprofileo.firebasestorage.app',
    measurementId: 'G-5VDD87LB8P',
  );
}
